//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotFrameworkDsl
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "botframeworkmodel";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"BotFrameworkDsl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"James Mann";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID BotFrameworkDslDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(BotFrameworkDslCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID BotFrameworkDslExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(BotFrameworkDslCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewBotFrameworkDslExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(BotFrameworkDslCommandSetId), 0x0001);
	
		// Package identifier
		public const string BotFrameworkDslPackageId = "b11c2986-8b42-4fa1-8f44-3dd353bca3e0";
		
		// Editor factory identifier
		public const string BotFrameworkDslEditorFactoryId = "12ab00b0-40fb-4c17-96e5-3c0a51bc9117";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string BotFrameworkDslModelExplorerToolWindowId = "6149a85b-b05e-444c-99c2-d463c7c3455e";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace BotFrameworkDsl
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string BotFrameworkDslCommandSetId = "09b1fcdb-f162-44c6-8774-219c2d45d3e3";
	}
}